### ISSUE TITLE
Cannot find module 'graceful-fs'

### ISSUE THREAD

**Issue by DaZiYuan** [punkave/mechanic#19]
get error when install  mechanic
ubuntu 18
node 10
```
npm install -g mechanic
```

```
/root/.nvm/versions/node/v10.15.3/bin/mechanic -> /root/.nvm/versions/node/v10.15.3/lib/node_modules/mechanic/bin/mechanic

> fs-ext@0.5.0 install /root/.nvm/versions/node/v10.15.3/lib/node_modules/mechanic/node_modules/fs-ext
> node-gyp configure build

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/mechanic/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@0.5.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-ext@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T07_10_59_217Z-debug.log
```

**Comment by boutell** [comment]
graceful-fs is a nested dependency of mechanic but it's properly specified and I don't have any trouble installing it.

I think you have a broken install of npm. See:

https://techoverflow.net/2012/10/07/how-to-fix-npm-cannot-find-module-graceful-fs-error/

My conjecture is that you can't `npm install -g` any other packages, either. Let me know if I'm mistaken though.

**Comment by stiv-yakovenko** [comment]
I have the same problem, i am able to require('graceful-fs'), but **node-gyp build** fails

**Comment by AappMoney** [comment]
Thanks

**Comment by greggwon** [comment]
There is something deeper that is wrong for me.  I've uninstalled, reinstalled and still have this problem.  

[pid 27634] prctl(PR_SET_NAME, "node-gyp") = 0
[pid 27634] getcwd("/home/abb/git/node-red-nodes/nodes/node-red-native", 4096) = 51
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/bin", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
[pid 27634] openat(AT_FDCWD, "/usr/share/node-gyp/package.json", O_RDONLY|O_CLOEXEC) = 20
[pid 27634] pread64(20, "{\n  \"name\": \"node-gyp\",\n  \"descr"..., 32768, 0) = 1061
[pid 27634] close(20)                   = 0
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/lib/node-gyp.js", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=4874, ...}) = 0
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/lib", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/lib/node-gyp.js", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=4874, ...}) = 0
[pid 27634] openat(AT_FDCWD, "/usr/share/node-gyp/lib/node-gyp.js", O_RDONLY|O_CLOEXEC) = 20
[pid 27634] statx(20, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=4874, ...}) = 0
[pid 27634] read(20, "\n/**\n * Module exports.\n */\n\nmod"..., 4874) = 4874
[pid 27634] close(20)                   = 0
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/lib/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/usr/share/node-gyp/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/usr/share/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/usr/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/home/abb/.node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/home/abb/.node_libraries", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] statx(AT_FDCWD, "/usr/lib/node", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb72ae180) = -1 ENOENT (No such file or directory)
[pid 27634] mprotect(0x2b7996104000, 503808, PROT_READ|PROT_WRITE) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_WRITE) = 0
[pid 27634] mprotect(0x2b7996104000, 503808, PROT_READ|PROT_EXEC) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_EXEC) = 0
[pid 27634] mprotect(0x2b7996104000, 503808, PROT_READ|PROT_WRITE) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_WRITE) = 0
[pid 27634] mprotect(0x2b7996104000, 503808, PROT_READ|PROT_EXEC) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_EXEC) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_WRITE) = 0
[pid 27634] mprotect(0x2b7996184000, 503808, PROT_READ|PROT_EXEC) = 0
[pid 27634] mmap(0x15be70280000, 1044480, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x15be70280000
[pid 27634] munmap(0x15be70300000, 520192) = 0
[pid 27634] mprotect(0x15be70280000, 524288, PROT_READ|PROT_WRITE) = 0
[pid 27634] write(2, "internal/modules/cjs/loader.js:6"..., 761internal/modules/cjs/loader.js:638
    throw err;
    ^

**Comment by SimonWesterlind** [comment]
I solved it by force replacing the installation of graceful-fs.
```
sudo npm install --force -g graceful-fs
```

**Comment by DulanjanaLakshan** [comment]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'graceful-fs'
Require stack:
- C:\Users\Dulan\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\tools\gracefulifyFs.js
- C:\Users\Dulan\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _gracefulFs (C:\Users\Dulan\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\tools\gracefulifyFs.js:19:39)
    at Object.<anonymous> (C:\Users\Dulan\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\tools\gracefulifyFs.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Dulan\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli\\build\\tools\\gracefulifyFs.js',
    'C:\\Users\\Dulan\\AppData\\Local\\npm-cache\\_npx\\7930a8670f922cdb\\node_modules\\@react-native-community\\cli\\build\\bin.js'
  ]
}

**Comment by boutell** [comment]
It looks like you're trying to use this under Windows, which won't work. It's for managing nginx running on Linux systems.
