### ISSUE TITLE
why mechanic install process needs nod.js to be installed before ?

### ISSUE THREAD

**Issue by erwin16** [punkave/mechanic#3]
I tried to follow your install prices , but I got a config error .... it's not stated in the doc that node.js is a requirement ... is not it ?  thanks for sharing

yves@legolas:~$ sudo npm install -g mechanic
npm http GET https://registry.npmjs.org/mechanic
npm http 304 https://registry.npmjs.org/mechanic
npm http GET https://registry.npmjs.org/boring
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/nunjucks
npm http GET https://registry.npmjs.org/prettiest
npm http GET https://registry.npmjs.org/shell-escape
npm http GET https://registry.npmjs.org/shelljs
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http GET https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz
npm http 200 https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http 200 https://registry.npmjs.org/nunjucks
npm http 200 https://registry.npmjs.org/prettiest
npm http 200 https://registry.npmjs.org/boring
npm http GET https://registry.npmjs.org/nunjucks/-/nunjucks-1.3.4.tgz
npm http GET https://registry.npmjs.org/prettiest/-/prettiest-0.1.0.tgz
npm http GET https://registry.npmjs.org/boring/-/boring-0.1.0.tgz
npm http 200 https://registry.npmjs.org/nunjucks/-/nunjucks-1.3.4.tgz
npm http 200 https://registry.npmjs.org/shell-escape
npm http GET https://registry.npmjs.org/shell-escape/-/shell-escape-0.2.0.tgz
npm http 200 https://registry.npmjs.org/boring/-/boring-0.1.0.tgz
npm http 200 https://registry.npmjs.org/shell-escape/-/shell-escape-0.2.0.tgz
npm http 200 https://registry.npmjs.org/prettiest/-/prettiest-0.1.0.tgz
npm http GET https://registry.npmjs.org/fs-ext
npm http 200 https://registry.npmjs.org/fs-ext
npm http GET https://registry.npmjs.org/fs-ext/-/fs-ext-0.4.6.tgz
npm http 200 https://registry.npmjs.org/fs-ext/-/fs-ext-0.4.6.tgz
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/chokidar
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz
npm http GET https://registry.npmjs.org/chokidar/-/chokidar-0.12.6.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz
npm http 200 https://registry.npmjs.org/chokidar/-/chokidar-0.12.6.tgz
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-1.9.0.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.9.0.tgz
npm http GET https://registry.npmjs.org/readdirp
npm http GET https://registry.npmjs.org/async-each
npm http GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/async-each
npm http 200 https://registry.npmjs.org/readdirp
npm http 200 https://registry.npmjs.org/fsevents
npm http GET https://registry.npmjs.org/async-each/-/async-each-0.1.6.tgz
npm http GET https://registry.npmjs.org/readdirp/-/readdirp-1.3.0.tgz
npm http GET https://registry.npmjs.org/fsevents/-/fsevents-0.3.8.tgz
npm http 200 https://registry.npmjs.org/async-each/-/async-each-0.1.6.tgz
npm http 200 https://registry.npmjs.org/readdirp/-/readdirp-1.3.0.tgz
npm http 200 https://registry.npmjs.org/fsevents/-/fsevents-0.3.8.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 200 https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz
npm WARN optional dep failed, continuing fsevents@0.3.8
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.3.tgz
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.3.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http 200 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 200 https://registry.npmjs.org/lru-cache
npm http 200 https://registry.npmjs.org/string_decoder
npm http 200 https://registry.npmjs.org/core-util-is
npm http 200 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
npm http GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm http 200 https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz
npm http 200 https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz

> fs-ext@0.4.6 install /usr/local/lib/node_modules/mechanic/node_modules/prettiest/node_modules/fs-ext
> node-gyp configure build

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-71-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/mechanic/node_modules/prettiest/node_modules/fs-ext
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by boutell** [comment]
It's an npm package (:

Yes, you need node to be installed.

But I don't really understand how you ran npm without node.

Maybe you have a path problem. But this is a normal requirement for
anything written in node.

On Mon, Jan 11, 2016 at 9:27 AM, yvesdufour <notifications@github.com>
wrote:

> I tried to follow your install prices , but I got a config error it's not
> stated in the doc that nodejs is a requirement is not it ? thanks for
> sharing
>
> yves@legolas:~$ sudo npm install -g mechanic
> npm http GET https://registrynpmjsorg/mechanic
> npm http 304 https://registrynpmjsorg/mechanic
> npm http GET https://registrynpmjsorg/boring
> npm http GET https://registrynpmjsorg/lodash
> npm http GET https://registrynpmjsorg/nunjucks
> npm http GET https://registrynpmjsorg/prettiest
> npm http GET https://registrynpmjsorg/shell-escape
> npm http GET https://registrynpmjsorg/shelljs
> npm http 200 https://registrynpmjsorg/lodash
> npm http 200 https://registrynpmjsorg/shelljs
> npm http GET https://registrynpmjsorg/lodash/-/lodash-242tgz
> npm http GET https://registrynpmjsorg/shelljs/-/shelljs-030tgz
> npm http 200 https://registrynpmjsorg/shelljs/-/shelljs-030tgz
> npm http 200 https://registrynpmjsorg/lodash/-/lodash-242tgz
> npm http 200 https://registrynpmjsorg/nunjucks
> npm http 200 https://registrynpmjsorg/prettiest
> npm http 200 https://registrynpmjsorg/boring
> npm http GET https://registrynpmjsorg/nunjucks/-/nunjucks-134tgz
> npm http GET https://registrynpmjsorg/prettiest/-/prettiest-010tgz
> npm http GET https://registrynpmjsorg/boring/-/boring-010tgz
> npm http 200 https://registrynpmjsorg/nunjucks/-/nunjucks-134tgz
> npm http 200 https://registrynpmjsorg/shell-escape
> npm http GET https://registrynpmjsorg/shell-escape/-/shell-escape-020tgz
> npm http 200 https://registrynpmjsorg/boring/-/boring-010tgz
> npm http 200 https://registrynpmjsorg/shell-escape/-/shell-escape-020tgz
> npm http 200 https://registrynpmjsorg/prettiest/-/prettiest-010tgz
> npm http GET https://registrynpmjsorg/fs-ext
> npm http 200 https://registrynpmjsorg/fs-ext
> npm http GET https://registrynpmjsorg/fs-ext/-/fs-ext-046tgz
> npm http 200 https://registrynpmjsorg/fs-ext/-/fs-ext-046tgz
> npm http GET https://registrynpmjsorg/optimist
> npm http GET https://registrynpmjsorg/chokidar
> npm http 200 https://registrynpmjsorg/optimist
> npm http 200 https://registrynpmjsorg/chokidar
> npm http GET https://registrynpmjsorg/optimist/-/optimist-061tgz
> npm http GET https://registrynpmjsorg/chokidar/-/chokidar-0126tgz
> npm http 200 https://registrynpmjsorg/optimist/-/optimist-061tgz
> npm http 200 https://registrynpmjsorg/chokidar/-/chokidar-0126tgz
> npm http GET https://registrynpmjsorg/nan
> npm http 200 https://registrynpmjsorg/nan
> npm http GET https://registrynpmjsorg/nan/-/nan-190tgz
> npm http 200 https://registrynpmjsorg/nan/-/nan-190tgz
> npm http GET https://registrynpmjsorg/readdirp
> npm http GET https://registrynpmjsorg/async-each
> npm http GET https://registrynpmjsorg/fsevents
> npm http 200 https://registrynpmjsorg/async-each
> npm http 200 https://registrynpmjsorg/readdirp
> npm http 200 https://registrynpmjsorg/fsevents
> npm http GET https://registrynpmjsorg/async-each/-/async-each-016tgz
> npm http GET https://registrynpmjsorg/readdirp/-/readdirp-130tgz
> npm http GET https://registrynpmjsorg/fsevents/-/fsevents-038tgz
> npm http 200 https://registrynpmjsorg/async-each/-/async-each-016tgz
> npm http 200 https://registrynpmjsorg/readdirp/-/readdirp-130tgz
> npm http 200 https://registrynpmjsorg/fsevents/-/fsevents-038tgz
> npm http GET https://registrynpmjsorg/wordwrap
> npm http GET https://registrynpmjsorg/minimist
> npm http 200 https://registrynpmjsorg/wordwrap
> npm http 200 https://registrynpmjsorg/minimist
> npm http GET https://registrynpmjsorg/wordwrap/-/wordwrap-003tgz
> npm http GET https://registrynpmjsorg/minimist/-/minimist-0010tgz
> npm http 200 https://registrynpmjsorg/wordwrap/-/wordwrap-003tgz
> npm http 200 https://registrynpmjsorg/minimist/-/minimist-0010tgz
> npm WARN optional dep failed, continuing fsevents@038
> npm http GET https://registrynpmjsorg/graceful-fs
> npm http GET https://registrynpmjsorg/minimatch
> npm http GET https://registrynpmjsorg/readable-stream
> npm http 200 https://registrynpmjsorg/graceful-fs
> npm http 200 https://registrynpmjsorg/minimatch
> npm http 200 https://registrynpmjsorg/readable-stream
> npm http GET https://registrynpmjsorg/graceful-fs/-/graceful-fs-203tgz
> npm http GET https://registrynpmjsorg/minimatch/-/minimatch-0214tgz
> npm http GET
> https://registrynpmjsorg/readable-stream/-/readable-stream-1033tgz
> npm http 200 https://registrynpmjsorg/graceful-fs/-/graceful-fs-203tgz
> npm http 200 https://registrynpmjsorg/minimatch/-/minimatch-0214tgz
> npm http 200
> https://registrynpmjsorg/readable-stream/-/readable-stream-1033tgz
> npm http GET https://registrynpmjsorg/sigmund
> npm http GET https://registrynpmjsorg/lru-cache
> npm http 200 https://registrynpmjsorg/sigmund
> npm http GET https://registrynpmjsorg/string_decoder
> npm http GET https://registrynpmjsorg/inherits
> npm http GET https://registrynpmjsorg/core-util-is
> npm http GET https://registrynpmjsorg/isarray/001
> npm http 200 https://registrynpmjsorg/lru-cache
> npm http 200 https://registrynpmjsorg/string_decoder
> npm http 200 https://registrynpmjsorg/core-util-is
> npm http 200 https://registrynpmjsorg/inherits
> npm http 200 https://registrynpmjsorg/isarray/001
> npm http GET https://registrynpmjsorg/sigmund/-/sigmund-101tgz
> npm http GET https://registrynpmjsorg/lru-cache/-/lru-cache-273tgz
> npm http GET
> https://registrynpmjsorg/string_decoder/-/string_decoder-01031tgz
> npm http GET https://registrynpmjsorg/core-util-is/-/core-util-is-102tgz
> npm http 200 https://registrynpmjsorg/sigmund/-/sigmund-101tgz
> npm http GET https://registrynpmjsorg/inherits/-/inherits-201tgz
> npm http GET https://registrynpmjsorg/isarray/-/isarray-001tgz
> npm http 200 https://registrynpmjsorg/lru-cache/-/lru-cache-273tgz
> npm http 200
> https://registrynpmjsorg/string_decoder/-/string_decoder-01031tgz
> npm http 200 https://registrynpmjsorg/core-util-is/-/core-util-is-102tgz
> npm http 200 https://registrynpmjsorg/inherits/-/inherits-201tgz
> npm http 200 https://registrynpmjsorg/isarray/-/isarray-001tgz
>
> fs-ext@046 install
> /usr/local/lib/node_modules/mechanic/node_modules/prettiest/node_modules/fs-ext
> node-gyp configure build
>
> /bin/sh: 1: node: not found
> gyp: Call to 'node -e "require('nan')"' returned exit status 127 while
> trying to load bindinggyp
> gyp ERR! configure error
> gyp ERR! stack Error: gyp failed with exit code: 1
> gyp ERR! stack at ChildProcessonCpExit
> (/usr/share/node-gyp/lib/configurejs:431:16)
> gyp ERR! stack at ChildProcessEventEmitteremit (eventsjs:98:17)
> gyp ERR! stack at ProcessChildProcess_handleonexit (child_processjs:797:12)
> gyp ERR! System Linux 3130-71-generic
> gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
> gyp ERR! cwd
> /usr/local/lib/node_modules/mechanic/node_modules/prettiest/node_modules/fs-ext
> gyp ERR! node -v v01025
> gyp ERR! node-gyp -v v01010
> gyp ERR! not ok
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/READMEDebian
>
> npm ERR! weird error 1
> npm ERR! not ok code 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/mechanic/issues/3>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
