### ISSUE TITLE
Issues installing on newer version of node

### ISSUE THREAD

**Issue by rwatts3** [punkave/mechanic#4]
Greetings,

I'm using the latest version of node, and i'm receiving errors.
Is there a recommended version of node to run this on ?

**Comment by rwatts3** [comment]
Looks like it works up to `0.12.14` Fails on newer versions using fs-ext.

**Comment by boutell** [comment]
Hmmm. We're mostly still on 0.10.x. Thoughts on why it fails?

On Thu, Jun 16, 2016 at 9:06 PM, Ryan Watts <notifications@github.com>
wrote:

> Looks like it works up to 0.12.14 Fails on newer versions using fs-ext.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/mechanic/issues/4#issuecomment-226656135>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAB9fbxTocR0_38FuocR3nb1T2lfu5UPks5qMfMCgaJpZM4I38nb>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I bet it's complaining about existsSync?

Grumble grumble totally unnecessary busybody dumb change not necessary for
the sync version and locking can be a higher level concern grumble grumble
grouse.

On Thu, Jun 16, 2016 at 9:19 PM, Tom Boutell <tom@punkave.com> wrote:

> Hmmm. We're mostly still on 0.10.x. Thoughts on why it fails?
>
> On Thu, Jun 16, 2016 at 9:06 PM, Ryan Watts <notifications@github.com>
> wrote:
>
>> Looks like it works up to 0.12.14 Fails on newer versions using fs-ext.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/punkave/mechanic/issues/4#issuecomment-226656135>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAB9fbxTocR0_38FuocR3nb1T2lfu5UPks5qMfMCgaJpZM4I38nb>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *SUPPORT LEAD
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Are you really getting errors, or just compilation warnings? That's all I
got with newer (or older) node and it has to do with fs-ext which is a
necessary dependency of prettiest, otherwise no file locking.

On Thu, Jun 16, 2016 at 9:20 PM, Tom Boutell <tom@punkave.com> wrote:

> I bet it's complaining about existsSync?
>
> Grumble grumble totally unnecessary busybody dumb change not necessary for
> the sync version and locking can be a higher level concern grumble grumble
> grouse.
>
> On Thu, Jun 16, 2016 at 9:19 PM, Tom Boutell <tom@punkave.com> wrote:
>
>> Hmmm. We're mostly still on 0.10.x. Thoughts on why it fails?
>>
>> On Thu, Jun 16, 2016 at 9:06 PM, Ryan Watts <notifications@github.com>
>> wrote:
>>
>>> Looks like it works up to 0.12.14 Fails on newer versions using fs-ext.
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/punkave/mechanic/issues/4#issuecomment-226656135>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AAB9fbxTocR0_38FuocR3nb1T2lfu5UPks5qMfMCgaJpZM4I38nb>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>> *THOMAS BOUTELL, *SUPPORT LEAD
>> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *SUPPORT LEAD
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Hi Tom, 

My apologies for such a late response. Thank you for following up.

The errors I'm getting are below.


```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/local/bin/mechanic -> /usr/local/lib/node_modules/mechanic/bin/mechanic
> fs-ext@0.4.6 install /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
> node-gyp configure build
make: Entering directory '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../../nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../../nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../fs-ext.cc:27:
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../fs-ext.cc:27:
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
fs-ext.target.mk:90: recipe for target 'Release/obj.target/fs-ext/fs-ext.o' failed
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /mechanic/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mechanic"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! fs-ext@0.4.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-ext@0.4.6 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fs-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fs-ext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fs-ext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryandwatts/npm-debug.log
npm ERR! code 1
```

**Comment by boutell** [comment]
This is a compiler error relating to the fs-ext module. We're using the
latest release of it (via our "prettiest" module) — not much more we can
do. I recommend you open an issue on the fs-ext module and be sure to
specify what operating system you got these results with.

On Sat, Jun 18, 2016 at 12:29 AM, Ryan Watts <notifications@github.com>
wrote:

> Hi Tom,
>
> My apologies for such a late response. Thank you for following up.
>
> The errors I'm getting are below.
>
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> /usr/local/bin/mechanic -> /usr/local/lib/node_modules/mechanic/bin/mechanic
> > fs-ext@0.4.6 install /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
> > node-gyp configure build
> make: Entering directory '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
>   CXX(target) Release/obj.target/fs-ext/fs-ext.o
> In file included from ../fs-ext.cc:27:0:
> ../../nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
>    NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
>                            ^
> ../../nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
>    v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
>                  ^
> ../../nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
>    NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
>                            ^
> ../../nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
>    NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
>                            ^
> ../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
>      , node::smalloc::FreeCallback callback
>              ^
> ../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
>      , node::smalloc::FreeCallback callback
>                                    ^
> ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
> ../../nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
>          v8::Isolate::GetCurrent(), data, length, callback, hint);
>                                                   ^
> ../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
>          v8::Isolate::GetCurrent(), data, length, callback, hint);
>                                                             ^
> ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
> ../../nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
>      return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
>                                                                    ^
> In file included from ../../nan/nan.h:25:0,
>                  from ../fs-ext.cc:27:
> /usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
>  NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
>                                         ^
> /usr/include/nodejs/src/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
> In file included from ../fs-ext.cc:27:0:
> ../../nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
>      return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
>                                                                    ^
> In file included from ../../nan/nan.h:25:0,
>                  from ../fs-ext.cc:27:
> /usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
>  NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
>                                         ^
> /usr/include/nodejs/src/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
> In file included from ../fs-ext.cc:27:0:
> ../../nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
>      return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
>                                                                    ^
> ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
> ../../nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
>      return node::Buffer::New(v8::Isolate::GetCurrent(), size);
>                              ^
> ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
> ../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
>      return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
>             ^fs-ext.target.mk:90: recipe for target 'Release/obj.target/fs-ext/fs-ext.o' failed
> make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
> make: Leaving directory '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 4.4.0-24-generic
> gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure" "build"
> gyp ERR! cwd /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
> gyp ERR! node -v v4.2.6
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! not ok
> /usr/local/lib
> └── (empty)
>
> npm WARN optional Skipping failed optional dependency /mechanic/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
> npm ERR! Linux 4.4.0-24-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mechanic"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
>
> npm ERR! fs-ext@0.4.6 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fs-ext@0.4.6 install script 'node-gyp configure build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the fs-ext package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs fs-ext
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls fs-ext
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ryandwatts/npm-debug.log
> npm ERR! code 1
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/mechanic/issues/4#issuecomment-226921229>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAB9fUYZPMtd24CRFLpcVGoFwhfVwQjqks5qM3QNgaJpZM4I38nb>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
node-gyp works fine without root for us. This could be specific to
permissions on your server(s).

However mechanic requires root to do its job, and so does npm install -g
(unless you change the npm root, but that wouldn't do you much good with
mechanic, which needs to edit nginx conf files and restart nginx).

On Mon, Jun 20, 2016 at 10:37 AM, Ryan Watts <notifications@github.com>
wrote:

> Hi Tom,
>
> Thank you. It turns out this was related to root permissions.
> If running the install as a user without root permissions, the install
> would proceed, however a non root user would not have access to node-gyp.
> In fact even adding your user to sudo still did not suffice. You have to
> actually run the install as the root user in order for it to to work
> properly.
>
> As I believed this was node version related, I can confirm this is the case
> at least for the node versions I tested.
>
> Assuming most people use root when working on their server, I'd imagine
> this is the reason most people don't see the error.
> On Mon, Jun 20, 2016 at 6:05 AM Tom Boutell <notifications@github.com>
> wrote:
>
>
> > This is a compiler error relating to the fs-ext module. We're using the
> > latest release of it (via our "prettiest" module) — not much more we can
> > do. I recommend you open an issue on the fs-ext module and be sure to
> > specify what operating system you got these results with.
> >
> > On Sat, Jun 18, 2016 at 12:29 AM, Ryan Watts <notifications@github.com>
> > wrote:
> >
> > > Hi Tom,
> > >
> > > My apologies for such a late response. Thank you for following up.
> > >
> > > The errors I'm getting are below.
> > >
> > > npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2
> > or higher to avoid a RegExp DoS issue
> > > npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before
> > will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0
> > as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> > > /usr/local/bin/mechanic ->
> > /usr/local/lib/node_modules/mechanic/bin/mechanic
> > > > fs-ext@0.4.6 install
> > /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
> > > > node-gyp configure build
> > > make: Entering directory
> > '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
> > > CXX(target) Release/obj.target/fs-ext/fs-ext.o
> > > In file included from ../fs-ext.cc:27:0:
> > > ../../nan/nan.h:324:27: error: redefinition of ‘template<class T>
> > v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
> > > NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T>
> > &val) {
> > > ^
> > > ../../nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T>
> > Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously
> declared
> > here
> > > v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
> > > ^
> > > ../../nan/nan.h:344:27: error: redefinition of ‘template<class T>
> > v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
> > > NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
> > > ^
> > > ../../nan/nan.h:334:27: note: ‘template<class T> v8::Local<T>
> > Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
> > > NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
> > > ^
> > > ../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
> > > , node::smalloc::FreeCallback callback
> > > ^
> > > ../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
> > > , node::smalloc::FreeCallback callback
> > > ^
> > > ../../nan/nan.h: In function ‘v8::Local<v8::Object>
> > NanNewBufferHandle(char*, size_t, int)’:
> > > ../../nan/nan.h:761:50: error: ‘callback’ was not declared in this
> scope
> > > v8::Isolate::GetCurrent(), data, length, callback, hint);
> > > ^
> > > ../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
> > > v8::Isolate::GetCurrent(), data, length, callback, hint);
> > > ^
> > > ../../nan/nan.h: In function ‘v8::Local<v8::Object>
> > NanNewBufferHandle(const char*, uint32_t)’:
> > > ../../nan/nan.h:768:67: error: no matching function for call to
> > ‘New(v8::Isolate*, const char*&, uint32_t&)’
> > > return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
> > > ^
> > > In file included from ../../nan/nan.h:25:0,
> > > from ../fs-ext.cc:27:
> > > /usr/include/nodejs/src/node_buffer.h:31:40: note: candidate:
> > v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*,
> > v8::Local<v8::String>, node::encoding) <near match>
> > > NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
> > > ^
> > > /usr/include/nodejs/src/node_buffer.h:31:40: note: conversion of
> > argument 3 would be ill-formed:
> > > In file included from ../fs-ext.cc:27:0:
> > > ../../nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka
> > unsigned int}’ to ‘node::encoding’ [-fpermissive]
> > > return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
> > > ^
> > > In file included from ../../nan/nan.h:25:0,
> > > from ../fs-ext.cc:27:
> > > /usr/include/nodejs/src/node_buffer.h:43:40: note: candidate:
> > v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
> > <near match>
> > > NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
> > > ^
> > > /usr/include/nodejs/src/node_buffer.h:43:40: note: conversion of
> > argument 2 would be ill-formed:
> > > In file included from ../fs-ext.cc:27:0:
> > > ../../nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to
> > ‘char*’ [-fpermissive]
> > > return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
> > > ^
> > > ../../nan/nan.h: In function ‘v8::Local<v8::Object>
> > NanNewBufferHandle(uint32_t)’:
> > > ../../nan/nan.h:772:29: error: could not convert
> > ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from
> > ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
> > > return node::Buffer::New(v8::Isolate::GetCurrent(), size);
> > > ^
> > > ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*,
> > uint32_t)’:
> > > ../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
> > > return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
> > > ^fs-ext.target.mk:90: recipe for target
>
> > 'Release/obj.target/fs-ext/fs-ext.o' failed
> > > make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
> > > make: Leaving directory
> > '/usr/local/lib/node_modules/mechanic/node_modules/fs-ext/build'
> > > gyp ERR! build error
> > > gyp ERR! stack Error: `make` failed with exit code: 2
> > > gyp ERR! stack at ChildProcess.onExit
> > (/usr/share/node-gyp/lib/build.js:269:23)
> > > gyp ERR! stack at emitTwo (events.js:87:13)
> > > gyp ERR! stack at ChildProcess.emit (events.js:172:7)
> > > gyp ERR! stack at Process.ChildProcess._handle.onexit
> > (internal/child_process.js:200:12)
> > > gyp ERR! System Linux 4.4.0-24-generic
> > > gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure"
> > "build"
> > > gyp ERR! cwd /usr/local/lib/node_modules/mechanic/node_modules/fs-ext
> > > gyp ERR! node -v v4.2.6
> > > gyp ERR! node-gyp -v v3.0.3
> > > gyp ERR! not ok
> > > /usr/local/lib
> > > └── (empty)
> > >
> > > npm WARN optional Skipping failed optional dependency
> > /mechanic/chokidar/fsevents:
> > > npm WARN notsup Not compatible with your operating system or
> > architecture: fsevents@0.3.8
> > > npm ERR! Linux 4.4.0-24-generic
> > > npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
> "mechanic"
> > > npm ERR! node v4.2.6
> > > npm ERR! npm v3.5.2
> > > npm ERR! code ELIFECYCLE
> > >
> > > npm ERR! fs-ext@0.4.6 install: `node-gyp configure build`
> > > npm ERR! Exit status 1
> > > npm ERR!
> > > npm ERR! Failed at the fs-ext@0.4.6 install script 'node-gyp configure
> > build'.
> > > npm ERR! Make sure you have the latest version of node.js and npm
> > installed.
> > > npm ERR! If you do, this is most likely a problem with the fs-ext
> > package,
> > > npm ERR! not with npm itself.
> > > npm ERR! Tell the author that this fails on your system:
> > > npm ERR! node-gyp configure build
> > > npm ERR! You can get information on how to open an issue for this
> > project with:
> > > npm ERR! npm bugs fs-ext
> > > npm ERR! Or if that isn't available, you can get their info via:
> > > npm ERR! npm owner ls fs-ext
> > > npm ERR! There is likely additional logging output above.
> > >
> > > npm ERR! Please include the following file with any support request:
> > > npm ERR! /home/ryandwatts/npm-debug.log
> > > npm ERR! code 1
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/punkave/mechanic/issues/4#issuecomment-226921229>,
> > or mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAB9fUYZPMtd24CRFLpcVGoFwhfVwQjqks5qM3QNgaJpZM4I38nb
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> >
> > *THOMAS BOUTELL, *SUPPORT LEAD
> > P'UNK AVENUE | (215) 755-1330 | punkave.com
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/punkave/mechanic/issues/4#issuecomment-227136279>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AFFsSUlD9p1Xz7Qs2Qis8bGJibFZ4YhYks5qNpAsgaJpZM4I38nb
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/mechanic/issues/4#issuecomment-227161048>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAB9fUpOr6dVi6SHU8-r5D-vTta3kLisks5qNqWagaJpZM4I38nb>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
You are right. I'm using Google Cloud Compute and I'm finding that they
have weird settings for a newly created instance. I have the solution
solved now.
Also all of their docs instruct you to use sudo ..... I'm sure somewhere I
overwrote the permissions for npm when using sudo commands.
